name = "gloria"
print(len(name))
print(name.find("g"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.isdigit())
print(name.isalpha())
print(name.count(""))
print(name.replace("o", "a"))
print(name*3)
